create database ddb;
show database;
create table Publisher (id int, name char(100), nation char(3));
show tables;
create table Customer (id int, name char(25), rank int);
create table Book (id int, title char(100), authors char(200), publisher_id int, copies int);
create table Orders (customer_id int, book_id int, quantity int);
create horizontal fragment Publisher.1 on Publisher id < 104000 AND nation = 'PRC';
allocate Publisher.1 to site1;
create horizontal fragment Publisher.2 on Publisher id < 104000 AND nation = 'USA';
allocate Publisher.2 to site2;
create horizontal fragment Publisher.3 on Publisher id >= 104000 AND nation = 'PRC';
allocate Publisher.3 to site3;
create horizontal fragment Publisher.4 on Publisher id >= 104000 AND nation = 'USA';
allocate Publisher.4 to site4;
create horizontal fragment Book.1 on Book id < 205000;
allocate Book.1 to site1;
create horizontal fragment Book.2 on Book id >= 205000 AND id < 210000;
allocate Book.2 to site2;
create horizontal fragment Book.3 on Book id >= 210000;
allocate Book.3 to site3;
create vertical fragment Customer.1 on Customer (id, name);
allocate Customer.1 to site1;
create vertical fragment Customer.2 on Customer (id, rank);
allocate Customer.2 to site2;
create horizontal fragment Orders.1 on Orders customer_id < 307000 and book_id < 215000;
allocate Orders.1 to site1;
create horizontal fragment Orders.2 on Orders customer_id < 307000 and book_id >= 215000;
allocate Orders.2 to site2;
create horizontal fragment Orders.3 on Orders customer_id >= 307000 and book_id < 215000;
allocate Orders.3 to site3;
create horizontal fragment Orders.4 on Orders customer_id >= 307000 and book_id >= 215000;
allocate Orders.4 to site4;
insert into Customer(id, name, rank) values(300001, 'Xiaoming', 1);
insert into Publisher(id, name, nation) values(104001,'High Education Press', 'PRC');
delete from Publisher where id = 104001;
delete from Customer where id = 300001;
load data Publisher,Customer,Orders,Book;
select Publisher.name from Publisher;
select * from Customer;
select Book.title from Book where copies>7000;
select customer_id, book_id from Orders;
select Book.title, Book.copies, Publisher.name, Publisher.nation from Book,Publisher where Book.publisher_id=Publisher.id and Publisher.nation='PRC'and Book.copies>1000;
select Customer.name, Book.title, Publisher.name, Orders.quantity from Customer,Book,Publisher,Orders where Customer.id=Orders.customer_id and Book.id=Orders.book_id and Book.publisher_id=Publisher.id and Book.id>210000 and Publisher.nation='PRC' and Orders.customer_id >= 307000 and Orders.book_id < 215000;